# Generated by Django 5.1 on 2025-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospitalalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalalert',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path='/path/to/your/output/dir'),
        ),
    ]
