# Generated by Django 5.1 on 2025-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospitalalert_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalalert',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='reports_hospital/'),
        ),
    ]
