# Generated by Django 5.1 on 2024-10-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaireview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('chai_varties', models.ManyToManyField(related_name='store', to='chai.chaivariety')),
            ],
        ),
    ]
