# Generated by Django 5.1 on 2024-10-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.TextField(),
        ),
    ]
